### ISSUE TITLE
Accessing the action output

### ISSUE THREAD

**Issue by chris3ware** [zoexx/github-action-json-file-properties#10]
Hi, I _think_ this is a silly question, but I am having trouble accessing the output from the action in subsequent steps.

This is my current workflow file:

```yaml
name: Scope

on:
  push: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  scopes:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Get commitlint scopes from configuration file
        id: commit_scope
        uses: zoexx/github-action-json-file-properties@1.0.6
        with:
          file_path: .commitlintrc.json
          prop_path: rules.scope-enum

      - run: |
          echo ${{ steps.commit_scope.outputs.value }}
```

I am testing the workflow with [act](https://github.com/nektos/act?tab=readme-ov-file) and I can see the values in the log output:

```log
[Scope/scopes]   ✅  Success - Main Get commitlint scopes from configuration file
[Scope/scopes]   ⚙  ::set-output:: 0=2
[Scope/scopes]   ⚙  ::set-output:: 1=always
[Scope/scopes]   ⚙  ::set-output:: 2=["checks","commitlint","delete-run","dep-review","get-token","pr-title","ossf","release","terraform-dir","terraform-docs","trunk","workflows"]
```

But the the `echo` statement to print them out is empty:

```
[Scope/scopes]   ⭐ Run Main echo ''
```

Have I misunderstood how to access the output? I thought that `value` should be substituted with the `key` so I have tried a few different combinations, for example:

```yaml
with:
  prop_path: rules

- run: |
    echo ${{ steps.commit_scope.outputs.scope-enum }}
```

Which produces a similar result. i.e. The `echo` returning a blank.

```
[Scope/scopes]   ✅  Success - Main Get commitlint scopes from configuration file
[Scope/scopes]   ⚙  ::set-output:: body-leading-blank=[1,"always"]
[Scope/scopes]   ⚙  ::set-output:: footer-leading-blank=[1,"always"]
[Scope/scopes]   ⚙  ::set-output:: header-max-length=[2,"always",72]
[Scope/scopes]   ⚙  ::set-output:: scope-enum=[2,"always",["checks","commitlint","delete-run","dep-review","get-token","pr-title","ossf","release","terraform-dir","terraform-docs","trunk","workflows"]]
...
⭐ Run Main echo ''
```

Thanks in advance for any assistance with this.
