### ISSUE TITLE
GitHub Action Error: Unable to resolve action zoexx/github-action-json-file-properties@release, unable to find version release

### ISSUE THREAD

**Issue by gayantharaka** [zoexx/github-action-json-file-properties#8]
First of all thank you for your contribution.  Our GitHub Action just started failing with the following message:
`Error: Unable to resolve action zoexx/github-action-json-file-properties@release, unable to find version release.
`
Our GitHub Action was working as expected before and today we got this error. Using checkout@v2 but I don't think that is the reason for this. 

```
uses: actions/checkout@v2 

- name: some_data: 
id :some_data 
uses: zoexx/github-action-json-file-properties@release
```

Does this issue have anything to do with latest update to this project? I went through this issue related to another project here: https://github.com/psf/black/issues/2079. 
Kindly check this. Thank you.

**Comment by trueberryless** [comment]
Same problem here: https://github.com/trueberryless-org/mutanuq/actions/runs/7912219925/workflow
This is a really nice action, for a moment I thought it would be achieved... Thank good, it is still alive xD

**Comment by trueberryless** [comment]
I temporarily used tag `1.0.6` and it works find... Maybe the `release` tag was removed?

```
      - name: read_json
        if: ${{ env.FILE_EXISTS == 'true' }}
        id: version
        uses: zoexx/github-action-json-file-properties@1.0.6
        with:
          file_path: ".github/artifacts/version.json"
```
